# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g2qXgRlPMr6z_fZkSPMBIc3mbcm-_CHj
"""

import streamlit as st
import pandas as pd
import plotly.express as px

# -----------------------------
# PAGE CONFIG
# -----------------------------
st.set_page_config(page_title="Ola Ride Dashboard", layout="wide")

# -----------------------------
# CUSTOM CSS
# -----------------------------
st.markdown("""
    <style>
    .main {
        background-color: #f5f7fa;
    }
    </style>
""", unsafe_allow_html=True)

# -----------------------------
# TITLE
# -----------------------------
st.title("🚖 Ola Ride Performance Dashboard")

# -----------------------------
# LOAD DATA
# -----------------------------
@st.cache_data
def load_data():
    return pd.read_csv("cleaned_ola_data.csv")

df = load_data()

# -----------------------------
# SIDEBAR FILTERS
# -----------------------------
st.sidebar.header("🔍 Filters")

vehicle = st.sidebar.multiselect("Vehicle Type", df['Vehicle_Type'].unique(), df['Vehicle_Type'].unique())
payment = st.sidebar.multiselect("Payment Method", df['Payment_Method'].unique(), df['Payment_Method'].unique())
day = st.sidebar.multiselect("Day", df['Day'].unique(), df['Day'].unique())

filtered_df = df[
    (df['Vehicle_Type'].isin(vehicle)) &
    (df['Payment_Method'].isin(payment)) &
    (df['Day'].isin(day))
]

# -----------------------------
# KPI SECTION
# -----------------------------
st.subheader("📊 Key Metrics")

col1, col2, col3, col4 = st.columns(4)

total_rides = len(filtered_df)
total_revenue = filtered_df['Booking_Value'].sum()
avg_ride_value = filtered_df['Booking_Value'].mean()
success_rate = 0 if total_rides == 0 else (
    filtered_df[filtered_df['Booking_Status'] == 'Success'].shape[0] / total_rides
) * 100

col1.metric("🚗 Total Rides", f"{total_rides:,}")
col2.metric("💰 Total Revenue", f"₹ {total_revenue:,.0f}")
col3.metric("📊 Avg Ride Value", f"₹ {avg_ride_value:,.0f}")
col4.metric("⭐ Success Rate", f"{success_rate:.2f}%")

# -----------------------------
# CHART ROW 1
# -----------------------------
col1, col2 = st.columns(2)

with col1:
    st.subheader("📈 Ride Volume by Day")
    day_order = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']
    temp = filtered_df.groupby('Day').size().reindex(day_order)

    fig1 = px.line(x=temp.index, y=temp.values, markers=True)
    fig1.update_layout(xaxis_title="Day", yaxis_title="Total Rides")
    st.plotly_chart(fig1, use_container_width=True)

with col2:
    st.subheader("💰 Revenue by Payment Method")
    temp = filtered_df.groupby('Payment_Method')['Booking_Value'].sum().reset_index()

    fig2 = px.bar(temp, x='Payment_Method', y='Booking_Value', color='Payment_Method')
    fig2.update_layout(yaxis_title="Revenue (₹)")
    st.plotly_chart(fig2, use_container_width=True)

# -----------------------------
# CHART ROW 2
# -----------------------------
col3, col4 = st.columns(2)

with col3:
    st.subheader("📌 Ride Outcome Distribution")

    temp = filtered_df['Booking_Status'].value_counts().reindex(
        df['Booking_Status'].unique(),
        fill_value=0
    ).reset_index()

    temp.columns = ['Status', 'Count']

    fig3 = px.pie(temp, names='Status', values='Count', hole=0.5)
    st.plotly_chart(fig3, use_container_width=True)

with col4:
    st.subheader("🚗 Ride Distribution by Vehicle Type")

    temp = filtered_df['Vehicle_Type'].value_counts().reset_index()
    temp.columns = ['Vehicle_Type', 'Count']

    fig4 = px.bar(temp, x='Vehicle_Type', y='Count', color='Vehicle_Type')
    fig4.update_layout(showlegend=False)  # ✅ removed legend
    st.plotly_chart(fig4, use_container_width=True)

# -----------------------------
# CHART ROW 3
# -----------------------------
col5, col6 = st.columns(2)

with col5:
    st.subheader("📏 Ride Distance Distribution")

    distance_df = filtered_df[filtered_df['Ride_Distance'] > 0]  # ✅ FIX

    fig5 = px.histogram(distance_df, x='Ride_Distance', nbins=30)
    st.plotly_chart(fig5, use_container_width=True)

with col6:
    st.subheader("⭐ Driver Ratings Distribution")

    fig6 = px.histogram(
        filtered_df[filtered_df['Driver_Ratings'] > 0],
        x='Driver_Ratings',
        nbins=10
    )
    st.plotly_chart(fig6, use_container_width=True)

# -----------------------------
# DATA TABLE
# -----------------------------
st.subheader("📋 Data Preview")
st.dataframe(filtered_df, use_container_width=True)